### ISSUE TITLE
Virtual keyboard by default

### ISSUE THREAD

**Issue by DraGiuS** [MarianArlt/sddm-sugar-light#2]
Hello, 
Why a virtual keyboard is set by default instead of the default setting ?

**Comment by MarianArlt** [comment]
Please could you be more specific? Are you sure it's not related to https://github.com/sddm/sddm/issues/952?

**Comment by Aurnytoraink** [comment]
I have the same issues.
When you click on the textarea to enter your password. The virtual keyboard grow up
But I'm on a desktop computer with a physical keyboard

**Comment by MarianArlt** [comment]
Could you please check your `/etc/sddm.conf` file and the default `/etc/sddm.conf.d/sddm.conf` file for `InputMethod`? If it has `virtualkeyboard` set, remove it. If there is no entry for `InputMethod` in any config file or it is empty, I would recommend uninstall `qt-virtualkeyboard` if you don't need it...This is an incredibly annoying issue with SDDM itself.

**Comment by Aurnytoraink** [comment]
Okay I will try, but if do that I will never have the Virtual keyboard ever.

Why we don't add a button like your other sddm theme ? 

https://github.com/MarianArlt/kde-plasma-chili

**Comment by MarianArlt** [comment]
There's a lot of coding involved in getting the virtual keyboard to work correctly. This is clearly an upstream issue, as SDDM has no default means to handle this relatively new function. We theme creators are held responsible when in reality this should have a sane default in SDDM itself.

I might adapt the Sugar themes in the future to work around this. Until then I'm sorry there is little choice when it comes to this subject. It's a major annoyance and I apologize but really, it shouldn't be the themes responsibility. It makes it look like a bug in the theme when it's a lack in the functionality of SDDM.

**Comment by DraGiuS** [comment]
I fixed it by doing the following command : 	
sed -i 's/InputMethod=qtvirtualkeyboard/InputMethod=/' /etc/sddm.conf
