### ISSUE TITLE
Translation & glitch graphics issues

### ISSUE THREAD

**Issue by Aurnytoraink** [MarianArlt/sddm-sugar-light#3]
Hi, this is my first time that I use this theme and I had some issue.
First the keyboard isssue [https://github.com/MarianArlt/sddm-sugar-light/issues/2](https://github.com/MarianArlt/sddm-sugar-light/issues/2)

And second, there is a problem with the translation:
The Welcome message is not translated. The suspend button text doesn't show up. The "show password" sentence is not translated.

In addition, in french we say "s'identifer" or "se connecter" instead of "identification"

![img_20181118_191617](https://user-images.githubusercontent.com/28545669/48677780-4ae72580-eb7a-11e8-8399-41d8ed8a86ef.jpg)

**Comment by MarianArlt** [comment]
This is partly an issue with SDDM itself and then with somebody not reading the README ;)
SDDM translations are very very lacking so I gave you guys the opportunity to translate EVERY element yourself. This can be done in the themes theme.conf file which can be found in the folder where SDDM gets the theme from. Usually this would be `/usr/share/sddm/themes/sugar-light/theme.conf`
Please see the [Sugar Wiki](https://github.com/MarianArlt/sddm-sugar-light/wiki/Translations) on translations for more detailed infos. Enjoy!
